version: "3"

services:
  db:
    image: postgres:16-bookworm
    restart: always
    ports:
      - "5432:5432"
    shm_size: 128mb

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "task-management"
